DROP TABLE IF EXISTS RESTAURANT;  
CREATE TABLE RESTAURANT (  
Id INT AUTO_INCREMENT  PRIMARY KEY,  
Name VARCHAR(250) NOT NULL,  
RestaurantType VARCHAR(100) NOT NULL,
Rating VARCHAR(250) NOT NULL,
Logo VARCHAR(250) NOT NULL,
CusineType VARCHAR(250) NOT NULL,
SeatingCapacity VARCHAR(250) NOT NULL,
OpenTime VARCHAR(250) NOT NULL,
CloseTime  VARCHAR(250) NOT NULL
);  

CREATE TABLE RESTAURANTS_2 (  
name VARCHAR(250) NOT NULL
);